name: Update @match in UserScript

on:
  push:
    paths:
      - black.txt  # Chỉ chạy khi black.txt thay đổi

jobs:
  update-match:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run update_matches.sh
        run: |
          chmod +x update_matches.sh
          ./update_matches.sh

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add anti-popup.user.js
          git commit -m "Update @match in UserScript based on changes to black.txt"
          git push
